Repository puppetlabs/puppetlabs-java, pull requests merged in 2018-11, with the labels that each got.

#315 MODULES-7819 fix set JAVA_HOME environments on FreeBSD platform
  manifests/config.pp
Labels: bugfix

#314 MODULES-8044: upgrade Oracle Java 8 to 181, make it the default release
  manifests/oracle.pp
  spec/defines/oracle_spec.rb
Labels: feature

#333 pdksync - pdksync_heads/master-0-gabccfb1
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#335 (FM-7520) - Removing Solaris from the support matrix
  metadata.json
Labels: bugfix
