Repository puppetlabs/puppetlabs-java, pull requests merged in 2019-07, with the labels that each got.

#371 (maint) Remove BSD section for puppet < 4
  README.markdown
Labels: maintenance

#373 pdksync - pdksync_heads/master-0-gb096033
  .rubocop.yml
  .travis.yml
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#374 Revert "Add support for debian buster"
  manifests/params.pp
Labels: bugfix

#375 (FM-8343) use release numbers not lsbdistcodename
  manifests/params.pp
  spec/classes/java_spec.rb
Labels: bugfix

#376 (FM-8223) converted to use litmus
  .fixtures.yml
  .sync.yml
  .travis.yml
  distelli-manifest.yml
  metadata.json
  provision.yaml
  spec/acceptance/install_spec.rb
  spec/acceptance/nodesets/centos-7-x64.yml
  spec/acceptance/nodesets/debian-8-x64.yml
  spec/acceptance/nodesets/default.yml
  spec/acceptance/nodesets/docker/centos-7.yml
  spec/acceptance/nodesets/docker/debian-8.yml
  spec/acceptance/nodesets/docker/ubuntu-14.04.yml
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
Labels: feature

#377 (maint) rerun pdk convert,remove systemtests gems
  Gemfile
Labels: maintenance

#372 [FM-8320] Remove Oracle download
  .rubocop.yml
  README.markdown
  manifests/download.pp
  spec/defines/download_spec.rb
  spec/defines/oracle_spec.rb
Labels: backwards-incompatible

#379 (MODULES-9604) Release prep - 5.0.0
  CHANGELOG.md
  metadata.json
Labels: maintenance
