Repository puppetlabs/puppetlabs-java, pull requests merged in 2019-04, with the labels that each got.

#356 pdksync - (MODULES-8444) - Raise lower Puppet bound
  metadata.json
Labels: backwards-incompatible

#353 (FM-7921) - Implement Puppet Strings
  README.markdown
  REFERENCE.md
  manifests/config.pp
  manifests/init.pp
  manifests/oracle.pp
  manifests/params.pp
Labels: feature

#358 pdksync - (maint) Update pdk-template to f778803
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  metadata.json
Labels: maintenance

#344 MODULES-8613: Add option to set a custom JCE download URL
  manifests/oracle.pp
Labels: feature
