Repository puppetlabs/puppetlabs-java, pull requests merged in 2019-11, with the labels that each got.

#395 (PDK-1501) Allow Travis CI config to be templated
  .rubocop.yml
  .sync.yml
  .travis.yml
  Gemfile
  Rakefile
  metadata.json
  spec/default_facts.yml
  spec/defines/download_spec.rb
Labels: maintenance

#396 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#398 pdksync - FM-8499 - remove ubuntu14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#397 MODULES-10062 - fix acceptance tests on sles
  spec/acceptance/install_spec.rb
Labels: bugfix

#399 (FM-8676) - Support added for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#400 Merge back release version v6.0.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#401 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .sync.yml
  .travis.yml
  Gemfile
  README.md
  metadata.json
Labels: maintenance
