Repository puppetlabs/puppetlabs-java, pull requests merged in 2022-10, with the labels that each got.

#527 pdksync - (CONT-130) - Dropping Support for Debian 9
  metadata.json
Labels: bugfix, hacktoberfest

#529 pdksync - (PDKSync) Removal of puppet_module_gems
  .devcontainer/README.md
  Gemfile
  metadata.json
Labels: maintenance, hacktoberfest

#525 Hardening manifests
  manifests/adopt.pp
  manifests/adoptium.pp
  manifests/config.pp
  manifests/download.pp
  spec/classes/java_spec.rb
  spec/defines/adopt_spec.rb
  spec/defines/adoptium_spec.rb
Labels: bugfix

#530 pdksync - (CONT-189) Remove support for RedHat6 / OracleLinux6 / Scientific6
  metadata.json
Labels: bugfix, hacktoberfest

#531 (CONT-173) - Updating deprecated facter instances
  lib/facter/java_default_home.rb
  lib/facter/java_version.rb
  spec/unit/facter/java_default_home_spec.rb
  spec/unit/facter/java_version_spec.rb
Labels: bugfix, hacktoberfest
