Repository puppetlabs/puppetlabs-java, pull requests merged in 2023-04, with the labels that each got.

#550 Fix shell_escape of unless command
  manifests/config.pp
  spec/classes/java_spec.rb
Labels: bugfix, community

#551 pdksync - (CONT-844) - Update .sync.yml
  .sync.yml
Labels: maintenance

#548 (CONT-784) Add Support for Puppet 8 / Drop Support for Puppet 6
  .devcontainer/devcontainer.json
  .fixtures.yml
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Rakefile
  lib/facter/java_default_home.rb
  lib/facter/java_version.rb
  metadata.json
  spec/acceptance/install_spec.rb
  spec/classes/java_spec.rb
  spec/defines/adopt_spec.rb
  spec/defines/adoptium_spec.rb
  spec/defines/download_spec.rb
  spec/defines/sap_spec.rb
  spec/spec_helper.rb
  spec/unit/facter/java_default_home_spec.rb
  spec/unit/facter/java_libjvm_path_spec.rb
  spec/unit/facter/java_major_version_spec.rb
  spec/unit/facter/java_patch_level_spec.rb
  spec/unit/facter/java_version_spec.rb
Labels: backwards-incompatible

#552 (maint) Release Prep v10.0.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#553 Revert "(CONT-784) Rubocop Manual Fixes 5 - RSpec/NoExpectationExample"
  .rubocop_todo.yml
  spec/acceptance/install_spec.rb
  spec/unit/facter/java_default_home_spec.rb
Labels: maintenance

#554 pdksync - (MAINT) - Remove deprecated has_key
  manifests/init.pp
Labels: maintenance
